#ifndef GCOMM_GCOMM_H
#define GCOMM_GCOMM_H
#include <cstdint>
#include "gcore.h"
#include "gbuffer.h"
#include "guart.h"
#include "guartbuffers.h"
#include "gsocketconnector.h"
#include "gmemconnector.h"
#include "gbufferconnector.h"
#endif //GCOMM_GCOMM_H